/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DatabasePaketi;

import Login.Admin;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author CeRaL
 */
public class BransGuncelle extends javax.swing.JFrame {

    Connection baglanti = null;
    PreparedStatement pst =null;
    ResultSet rs = null;
    /**
     * Creates new form BransEkle
     */
    public BransGuncelle() {
        initComponents();
        //listele();
    }
    
    public void baglanti () {
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Driver Sürücüsü Hatası : "+e.getMessage());
        }        
        try {
            baglanti= DriverManager.getConnection("jdbc:mysql://localhost:3308/hys?serverTimezone=UTC","root","");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bağlantı Hatası : "+e.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtBI = new javax.swing.JTextField();
        txtBA = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBrans = new javax.swing.JTable();
        btnEkle = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnGuncel = new javax.swing.JButton();
        btnListe = new javax.swing.JButton();
        btnGeri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Branş İşlemleri");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setText("Branş İşlemleri");

        jLabel2.setText("Branş ID : ");

        jLabel3.setText("Branş Adı :");

        tblBrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBrans);

        btnEkle.setText("EKLE");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        btnSil.setText("SİL");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnGuncel.setText("GÜNCELLE");
        btnGuncel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelActionPerformed(evt);
            }
        });

        btnListe.setText("LİSTELE");
        btnListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeActionPerformed(evt);
            }
        });

        btnGeri.setText("GERİ");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBA))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBI, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnListe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnEkle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSil)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGuncel))
                            .addComponent(btnGeri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtBI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtBA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEkle)
                            .addComponent(btnSil)
                            .addComponent(btnGuncel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnListe)
                            .addComponent(btnGeri)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        if(ekleKontrol()) ekle();
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        if(silKontrol()) sil();
    }//GEN-LAST:event_btnSilActionPerformed

    private void btnGuncelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelActionPerformed
        if(duzeltmeKontrol()) guncelle();
    }//GEN-LAST:event_btnGuncelActionPerformed

    private void btnListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeActionPerformed
        listele();
    }//GEN-LAST:event_btnListeActionPerformed

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        Admin adm = new Admin();
        adm.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnGeriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BransGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BransGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BransGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BransGuncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BransGuncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnGuncel;
    private javax.swing.JButton btnListe;
    private javax.swing.JButton btnSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBrans;
    private javax.swing.JTextField txtBA;
    private javax.swing.JTextField txtBI;
    // End of variables declaration//GEN-END:variables
public void ekle() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        baglanti();
        try {
            PreparedStatement uygula = baglanti.prepareStatement("INSERT INTO brans(Brans_adi) VALUES (?)");
            //uygula.setInt(1,Integer.valueOf(txtBI.getText()));
            uygula.setString(1,txtBA.getText());
            
            int donut=uygula.executeUpdate();
            if(donut>0)JOptionPane.showMessageDialog(null, "Kayıt Yapıldı");
            else JOptionPane.showMessageDialog(null, "Kayıt Esnasında Hata Oluştu");
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Güncelleme Hatası : "+e.getMessage());
        }
    }
public void sil() {
    baglanti();
        try {
            PreparedStatement uygula = baglanti.prepareStatement("DELETE FROM brans WHERE brans_id=?");
            uygula.setInt(1,Integer.valueOf(txtBI.getText()));
            
            int donut=uygula.executeUpdate();
            if(donut>0)JOptionPane.showMessageDialog(null, "Kayıt Silindi");
            else JOptionPane.showMessageDialog(null, "Silme Esnasında Hata Oluştu");
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Güncelleme Hatası : "+e.getMessage());
        }
    }
public void guncelle() {
    baglanti();
    try {
        PreparedStatement uygula = baglanti.prepareStatement("UPDATE brans SET Brans_adi=? WHERE brans_id=?");
            
        uygula.setString(1,txtBA.getText());
        uygula.setInt(2,Integer.valueOf(txtBI.getText()));
            
            int donut=uygula.executeUpdate();
            if(donut>0)JOptionPane.showMessageDialog(null, "Güncelleme Yapıldı");
            else JOptionPane.showMessageDialog(null, "Güncelleme Esnasında Hata Oluştu");
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Güncelleme Hatası : "+e.getMessage());
        }
    }
private boolean duzeltmeKontrol(){
        boolean donut = false;
        String mesaj = "";
        
        if(txtBI.getText().isEmpty()) mesaj=mesaj+"Branş ID boş bırakılamaz.\n";
        if(txtBA.getText().isEmpty()) mesaj=mesaj+"Branş Adı boş bırakılamaz.\n";
        
        if(mesaj=="") donut=true;
        else JOptionPane.showMessageDialog(null, mesaj);
        return donut;
    }
private boolean silKontrol(){
        boolean donut = false;
        String mesaj = "";
        
        if(txtBI.getText().isEmpty()) mesaj=mesaj+"Lütfen ID giriniz.";
        
        if(mesaj=="") donut=true;
        else JOptionPane.showMessageDialog(null, mesaj);
        return donut;
    }
private boolean ekleKontrol(){
        boolean donut = false;
        String mesaj = "";
        
        if(txtBA.getText().isEmpty()) mesaj=mesaj+"Lütfen Branş Adı giriniz.\n";
        
        if(mesaj=="") donut=true;
        else JOptionPane.showMessageDialog(null, mesaj);
        return donut;
    }
private void listele() {
    baglanti();       
        try {
            //baglanti= DriverManager.getConnection("jdbc:mysql://localhost:3308/hys?serverTimezone=UTC","root","");
            String ceral = "SELECT * FROM brans";
            pst = baglanti.prepareStatement(ceral);
            rs=pst.executeQuery();
            tblBrans.setModel(DbUtils.resultSetToTableModel(rs));
                        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Hata : "+e.getMessage());
        }       
    }
}

