/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DatabasePaketi;


import Login.Admin;
import hastane_yonetim_sistemi.IKayitEkle;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
//import.java.sql.Connection;

/**
 *
 * @author CeRaL
 */
public class PersonelEkle extends javax.swing.JFrame implements IKayitEkle{

        Connection baglan = null;
        
    PreparedStatement pst =null;
    ResultSet rs = null;
    /**
     * Creates new form PersonelEkle
     */
    public PersonelEkle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTC = new javax.swing.JTextField();
        txtAd = new javax.swing.JTextField();
        txtSoyad = new javax.swing.JTextField();
        txtTlf = new javax.swing.JTextField();
        btnTamam = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnGeri = new javax.swing.JButton();
        txtPt = new javax.swing.JTextField();
        btnListe = new javax.swing.JButton();
        cmbBrans = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Personel Kayıt");

        jLabel1.setText("Personel Tipi : ");

        jLabel2.setText("TC No:");

        jLabel3.setText("Adı :");

        jLabel4.setText("Soyadı :");

        jLabel5.setText("Branş");

        jLabel6.setText("Telefon :");

        btnTamam.setBackground(new java.awt.Color(0, 204, 0));
        btnTamam.setText("KAYDET");
        btnTamam.setBorderPainted(false);
        btnTamam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamamActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel7.setText("Personel Kayıt");

        btnGeri.setBackground(new java.awt.Color(255, 0, 51));
        btnGeri.setText("GERİ");
        btnGeri.setBorderPainted(false);
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        btnListe.setText("LİSTELE");
        btnListe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeActionPerformed(evt);
            }
        });

        cmbBrans.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbBransMouseClicked(evt);
            }
        });
        cmbBrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(44, 44, 44))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTC)
                                .addComponent(txtAd)
                                .addComponent(txtSoyad)
                                .addComponent(txtTlf, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addComponent(txtPt)
                                .addComponent(cmbBrans, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnListe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(btnGeri, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTamam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbBrans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnTamam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGeri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListe)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void baglanti () {
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Driver Sürücüsü Hatası : "+e.getMessage());
        }        
        try {
            baglan= DriverManager.getConnection("jdbc:mysql://localhost:3308/hys?serverTimezone=UTC","root","");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bağlantı Hatası : "+e.getMessage());
        }
    }
    private void listeleme() {
     
    try{
            try {
                baglanti();
            } catch (Exception e) {
                Logger.getLogger(SekreterRandevu.class.getName()).log(Level.SEVERE, null, e);
            }
        String sorgu = "select * from brans";

        pst = baglan.prepareStatement(sorgu);
        rs=pst.executeQuery();
        rs.last();
        int ks = rs.getRow();
        String kss=""+ks;
        if(ks>0) {
            rs.beforeFirst();
            while (rs.next()) {
                cmbBrans.addItem(rs.getString("brans_id"));
            }
        }
        else
            JOptionPane.showConfirmDialog(null,"Kayıtlı Branş Yok");
    } catch (SQLException ex){
            Logger.getLogger(SekreterRandevu.class.getName()).log(Level.SEVERE,null,ex);
        JOptionPane.showConfirmDialog(null,"hata");
        }   
    }
    
    private void btnTamamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamamActionPerformed
        if(ekleKontrol()) ekle();

    }//GEN-LAST:event_btnTamamActionPerformed

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
         Admin adm = new Admin();
         adm.setVisible(true);
          this.hide();
            // TODO add your handling code here:
    }//GEN-LAST:event_btnGeriActionPerformed

    private void btnListeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeActionPerformed
        PersonelListele listele = new PersonelListele();
         listele.setVisible(true);
          this.hide();
    }//GEN-LAST:event_btnListeActionPerformed

    private void cmbBransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBransActionPerformed
       // listeleme();
    }//GEN-LAST:event_cmbBransActionPerformed

    private void cmbBransMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbBransMouseClicked
       listeleme();
    }//GEN-LAST:event_cmbBransMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnListe;
    private javax.swing.JButton btnTamam;
    private javax.swing.JComboBox<String> cmbBrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtPt;
    private javax.swing.JTextField txtSoyad;
    private javax.swing.JTextField txtTC;
    private javax.swing.JTextField txtTlf;
    // End of variables declaration//GEN-END:variables

    @Override
    public void ekle() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Driver Sürücüsü Hatası : "+e.getMessage());
            
        }
        
        try {
            baglan= DriverManager.getConnection("jdbc:mysql://localhost:3308/hys?serverTimezone=UTC","root","");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Bağlantı Hatası : "+e.getMessage());
        }
        try {
            PreparedStatement uygula = baglan.prepareStatement("INSERT INTO p_tablo( P_tur, Tc, Ad, Soyad, brans_id, Telefon) VALUES (?,?,?,?,?,?)");
            uygula.setString(1,txtPt.getText());
            uygula.setString(2,txtTC.getText());
            uygula.setString(3,txtAd.getText());
            uygula.setString(4,txtSoyad.getText());
            //uygula.setInt(5,Integer.valueOf(txtBrans.getText()));
            uygula.setString(5, (String)cmbBrans.getSelectedItem());
            uygula.setString(6,txtTlf.getText());
            
            int donut=uygula.executeUpdate();
            if(donut>0)JOptionPane.showMessageDialog(null, "Kayıt Yapıldı");
            else JOptionPane.showMessageDialog(null, "Kayıt Esnasında Hata Oluştu");
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Güncelleme Hatası : "+e.getMessage());
        }
    }
    
    private boolean ekleKontrol(){
        boolean donut = false;
        String mesaj = "";
        
        if(txtPt.getText().isEmpty()) mesaj=mesaj+"Personel Tipi boş bırakılamaz.\n";
        if(txtTC.getText().isEmpty()) mesaj=mesaj+"TC Numarası boş bırakılamaz.\n";
        if(txtAd.getText().isEmpty()) mesaj=mesaj+"Personel Adı boş bırakılamaz.\n";
        if(txtSoyad.getText().isEmpty()) mesaj=mesaj+"Personel Soyadı boş bırakılamaz.\n";
        //if(txtBrans.getText().isEmpty()) mesaj=mesaj+"Branş boş bırakılamaz.\n";
        if(txtTlf.getText().isEmpty()) mesaj=mesaj+"Telefon boş bırakılamaz.\n";
        
        if(mesaj.equals("")) donut=true;
        else JOptionPane.showMessageDialog(null, mesaj);
        return donut;
    }

}
